### ISSUE TITLE
(Solved) Add a github 'release' or chucklefish forums link for people who don't use steam please

### ISSUE THREAD

**Issue by Parahacker** [AngryTurret/K-Rakoth-Mod#201]
As the title says.

I mean it's actually pretty easy just to download the folder and plop it into the mods folder from here, but adding regular releases to your git page creates a history of 'stable' version changes etc. that's easier to track than on your steam workshop account.

Or use the Chucklefish forums mod area.

I won't harass you with all the reasons I hate Steam, but I will say there's a bunch of us out there. And your mod is amazing, I really want to keep it up to date if possible. Thanks :)

**Comment by AngryTurret** [comment]
Thank you for a suggestion, now you can download the v1.3.5 release!

**Comment by Parahacker** [comment]
Thank you so much!
