### ISSUE TITLE
(Solved) Suggestion: Enhanced Storage compatability patch

### ISSUE THREAD

**Issue by Parahacker** [AngryTurret/K-Rakoth-Mod#202]
Enhanced storage really adds a lot to the usability of containers. If you haven't already, check it out, it makes a huge difference!

Cheers!

**Comment by AngryTurret** [comment]
Admittedly I've never used this mod before but I'll check it out.

**Comment by AngryTurret** [comment]
UPD: I was given all the necessary files to make a built-in support. They will be introduced with the next major update.
