### ISSUE TITLE
(Solved) Suggestion: make compatibility patches available on Git and/or Chucklefish

### ISSUE THREAD

**Issue by Parahacker** [AngryTurret/K-Rakoth-Mod#203]
Lol, sorry for being so demanding.

There are ways to scrape the compatibility patches from Steam for non-steam users, but I think it'd be both more accessible for non-Steam users and easier to maintain in the long run if the compatibility patches were all posted on Git - since you seem to be the primary author for them, so anyone looking for compatibility patches or addons done by you only needs to click your name here to find them.

Chucklefish forums are more troublesome to keep up to date, but you can link to your Git from there on the main K'rakoth mod page regarding any and all addons you maintain, so you don't need to maintain separate pages for each of them.

I've already got the compat patches I'd need by... methods... :) but for other GOG nebbishes (or heaven forbid, people who ordered in open beta before it was all Steamified and you could download directly from the Chucklefish site... sigh, nostalgia) this would hopefully strike a good balance between making compatability available while keeping maintenance overhead lower.

Cheers!

**Comment by Armokthespideroverlord** [comment]
I second the idea of putting the patches on git too, would allow for me to easily supply editorial work for them to as I've been doing with the main mod here, as well as contribute things for the Project Redemption patch I co-authored.

**Comment by AngryTurret** [comment]
I'll probably create a single repository for all the patches this week.

**Comment by AngryTurret** [comment]
Alright, I've finally created [a separate repository](https://github.com/AngryTurret/K-Rakoth-Mod-Patches) and included most of the existing patches there.
